"""State machine values for the fixed IMS VoLTE demo flow."""

from enum import Enum


class ClientState(str, Enum):
    INIT = "INIT"
    NETWORK_READY = "NETWORK_READY"
    TCP_CONNECTED = "TCP_CONNECTED"
    REGISTER_SENT = "REGISTER_SENT"
    AKA_CHALLENGE_RECEIVED = "AKA_CHALLENGE_RECEIVED"
    IPSEC_READY = "IPSEC_READY"
    REGISTERED = "REGISTERED"
    INVITE_SENT = "INVITE_SENT"
    SMS_SENT = "SMS_SENT"
    EARLY_DIALOG = "EARLY_DIALOG"
    CALL_ESTABLISHED = "CALL_ESTABLISHED"
    MEDIA_RUNNING = "MEDIA_RUNNING"
    TERMINATING = "TERMINATING"
    TERMINATED = "TERMINATED"
    FAILED = "FAILED"
